mutation CreateUser($data: UserCreateInput!) {
  createUser(data: $data) {
    id
  }
}

query CurrentUserOTP($key: String!) {
  currentUserOTP(key: $key)
}
mutation ValidateUserOTP($key: String!, $otp: String!) {
  validateUserOTP(key: $key, otp: $otp)
}

mutation SendUserPasswordResetLink($phoneNumber: String!) {
  sendUserPasswordResetLink(phoneNumber: $phoneNumber)
}

mutation RedeemUserPasswordResetToken(
  $phoneNumber: String!
  $token: String!
  $password: String!
) {
  redeemUserPasswordResetToken(
    phoneNumber: $phoneNumber
    token: $token
    password: $password
  ) {
    code
    message
  }
}

query ValidateUserPasswordResetToken($token: String!, $phoneNumber: String!) {
  validateUserPasswordResetToken(token: $token, phoneNumber: $phoneNumber) {
    code
    message
  }
}

mutation CreateDealer($data: DealerCreateInput!) {
  createDealer(data: $data) {
    id
  }
}
mutation AuthenticateUserWithPassword(
  $phoneNumber: String!
  $password: String!
) {
  authenticateUserWithPassword(phoneNumber: $phoneNumber, password: $password) {
    ... on UserAuthenticationWithPasswordSuccess {
      item {
        id
        name
        phoneNumber
        email
        address
        phoneNumberVerified
        isAdmin
        profile_image {
          id
          filesize
          width
          height
          extension
          url
        }
        addresses {
          id
          createdAt
          modifiedAt
          name
          phoneNumber
          pinCode
          address
          town
          district
          state
          default
        }
        emailVerified
        referralCode {
          id
          code
          modifiedAt
          createdAt
        }
        deactivate
      }
      sessionToken
    }
    ... on UserAuthenticationWithPasswordFailure {
      message
    }
  }
}

query User($where: UserWhereUniqueInput!) {
  user(where: $where) {
    id
    name
    phoneNumber
    email
    address
    phoneNumberVerified
    isAdmin
    profile_image {
      id
      filesize
      width
      height
      extension
      url
    }
    addresses {
      id
      createdAt
      modifiedAt
      name
      phoneNumber
      pinCode
      address
      town
      district
      state
      default
    }
    emailVerified
    referralCode {
      id
      code
      modifiedAt
      createdAt
    }
    favorites {
      vehicleVariant {
        id
      }
      id
    }
    aadhaar {
      url
      filename
    }
    driving_license {
      url
      filename
    }
    deactivate
  }
}

mutation UpdateUser($data: UserUpdateInput!, $where: UserWhereUniqueInput!) {
  updateUser(data: $data, where: $where) {
    id
  }
}

query Dealer($where: DealerWhereInput!) {
  dealers(where: $where) {
    id
    approved
    mouApproved
  }
}

mutation UpdateDealer($where: DealerWhereUniqueInput!, $data: DealerUpdateInput!) {
  updateDealer(where: $where, data: $data) {
    id
    lLat
    lLng
    location
  }
}

mutation SendDealerMOUApprovalOTP {
  sendDealerMOUApprovalOTP
}
