import 'dart:async';
import 'dart:developer' as developer;

import 'package:dealerapp/src/app/repository/graphql/__generated__/schema.schema.gql.dart';
import 'package:dealerapp/src/utils/constants.dart';
import 'package:dealerapp/src/utils/log_colors.dart';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:sentry_flutter/sentry_flutter.dart';

///Extensions for logging
extension Log on Object? {
  ///Overrides the [developer.log(message)] method with a custom implementation
  void log({
    String name = 'Log',
    String color = LogColors.black,
    String bgColor = LogColors.blackBg,
    Object? error,
    int level = 0,
    int? sequenceNumber,
    StackTrace? stackTrace,
  }) {
    if (Constants.shouldTrack) {
      if (this is Exception) {
        Sentry.captureException(
          this,
          stackTrace: stackTrace,
        );
      }
    }
    developer.log(
      '$color ${DateFormat('yyyy-MM-dd HH:mm:ss').format(DateTime.now())} $this ${LogColors.black}',
      name: color + name + LogColors.black,
      error: error,
      level: level,
      sequenceNumber: sequenceNumber,
      stackTrace: stackTrace,
      time: DateTime.now(),
      zone: Zone.current,
    );
  }
}

/// This is a extension for color
extension HexColor on Color {
  /// String is in the format "aabbcc" or "ffaabbcc" with an optional leading "#".
  static Color fromHex(String hexString) {
    final buffer = StringBuffer();
    if (hexString.length == 6 || hexString.length == 7) buffer.write('ff');
    buffer.write(hexString.replaceFirst('#', ''));
    try {
      return Color(int.parse(buffer.toString(), radix: 16));
    } catch (e) {
      return Colors.white;
    }
  }

  /// Prefixes a hash sign if [leadingHashSign] is set to `true` (default is `true`).
  String toHex({bool leadingHashSign = true}) => '${leadingHashSign ? '#' : ''}'
      '${alpha.toRadixString(16).padLeft(2, '0')}'
      '${red.toRadixString(16).padLeft(2, '0')}'
      '${green.toRadixString(16).padLeft(2, '0')}'
      '${blue.toRadixString(16).padLeft(2, '0')}';
}

/// This is a extension for int
extension NumExtenstions on num? {
  /// This method is used to convert int to price
  String toPrice() {
    final oCcy = NumberFormat('#,##,##0', 'en_IN');
    final data = oCcy.format(this);
    return '${Constants.rupee} $data';
  }

  /// This with normalze the value between 0 and given max value
  double normalize(double max, [double min = 0]) {
    if (this == null) return 0;
    return (this! - min) / (max - min);
  }

  /// This with denormalze the value between 0 and given max value
  double denormalize(double max, [double min = 0]) {
    if (this == null) return 0;
    return ((this! / max) / 100) * (max - min) + min;
  }
}

/// This is a extension for GDateTime
/// GDateTime is a type generated by graphql for date
extension GDateExtentions on GDateTime? {
  /// Returns the date time from GDateTime
  DateTime? get toDateTime => this != null ? DateTime.parse(this!.value) : null;

  /// Returns whether the date is today
  bool get isToday => toDateTime.isToday;

  /// Returns whether the date is in past 7 days
  bool get isPast7Days => toDateTime.isPast7Days;

  /// Returns the date in MMM dd, yyyy hh:mm a format
  /// Example: Jan 01, 2021 12:00 AM
  String get formatToMMMddyyyyhhmma => toDateTime.formatToMMMddyyyyhhmma;

  String get formatTohhmmaddMMyy => toDateTime.formatTohhmmaddMMyy;
}

/// This is a extension for DateTime
extension DateExtensions on DateTime? {
  /// Returns whether the date is today
  bool get isToday {
    if (this == null) {
      return false;
    }
    final now = DateTime.now();
    return now.year == this!.year &&
        now.month == this!.month &&
        now.day == this!.day;
  }

  /// Returns whether the date is in past 7 days
  bool get isPast7Days {
    if (this == null) {
      return false;
    }
    final now = DateTime.now();
    final diff = now.difference(this!);
    return diff.inDays <= 7;
  }

  /// Returns the date in MMM dd, yyyy hh:mm a format
  /// Example: Jan 01, 2021 12:00 AM
  String get formatToMMMddyyyyhhmma =>
      DateFormat('MMM dd, yyyy hh:mm a').format(this ?? DateTime.now());

  String get formatTohhmmaddMMyy =>
      DateFormat('hh:mm a dd/MM/yy').format(this ?? DateTime.now());
}
