targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: dealerapp|lib/src/app/repository/graphql/schema.graphql
          type_overrides:
            JSON:
              name: JsonObject
              import: "package:built_value/json_object.dart"
            Upload:
              name: MultipartFile
              import: "package:http/http.dart"
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: dealerapp|lib/src/app/repository/graphql/schema.graphql
          custom_serializers:
            - import: "package:built_value/src/json_object_serializer.dart"
              name: JsonObjectSerializer
            - import: "package:dealerapp/src/custom_serializers/upload_serializer.dart"
              name: UploadSerializer
