query VehicleOrders(
  $orderBy: [VehicleOrderOrderByInput!]!
  $where: VehicleOrderWhereInput!
) {
  vehicleOrders(orderBy: $orderBy, where: $where) {
    id
    price
    dealer {
      vehicleVariant {
        vehicle {
          name
        }
        name
        price
      }
      vehicleColor {
        name
        code
        images {
          id
          image {
            id
            url
          }
        }
      }
      dealer {
        id
      }
      id
      dealer_prices
    }
    status
    order {
      user {
        id
        email
        name
        phoneNumber
        addresses {
          id
          phoneNumber
          pinCode
          state
          town
          address
          district
          name
        }
      }
      id
      createdAt
    }
    createdAt
  }
}

query TestDriveOrders($where: TestDriveOrderWhereInput!, $orderBy: [TestDriveOrderOrderByInput!]!) {
  testDriveOrders(where: $where, orderBy: $orderBy) {
    id
    price
    dealer {
      vehicleVariant {
        vehicle {
          name
        }
        name
        price
      }
      vehicleColor {
        name
        code
        images {
          id
          image {
            id
            url
          }
        }
      }
      dealer {
        id
      }
      id
      price
    }
    status
    order {
      user {
        id
        email
        name
        phoneNumber
        addresses {
          id
          phoneNumber
          pinCode
          state
          town
          address
          district
          name
        }
      }
      id
      createdAt
    }
    createdAt
  }
}

mutation UpdateVehicleOrder(
  $where: VehicleOrderWhereUniqueInput!
  $data: VehicleOrderUpdateInput!
) {
  updateVehicleOrder(where: $where, data: $data) {
    id
  }
}

mutation CreateOrderRejectionByDealer($data: OrderRejectionByDealerCreateInput!) {
  createOrderRejectionByDealer(data: $data) {
    id
  }
}