query ProductOrders($where: ProductOrderWhereInput!, $orderBy: [ProductOrderOrderByInput!]!) {
  productOrders(where: $where, orderBy: $orderBy) {
    id
    price
    dealer {
      productVariant {
        product {
          name
        }
        name
        images {
          image {
            url
          }
        }
      }
      dealer {
        id
      }
      id
      prices {
        amount
        category {
          name
          id
        }
      }
    }
    status
    order {
      user {
        id
        email
        name
        phoneNumber
        addresses {
          id
          phoneNumber
          pinCode
          state
          town
          address
          district
          name
        }
      }
      id
      createdAt
    }
    createdAt
  }
}

query VehicleOrders(
  $orderBy: [VehicleOrderOrderByInput!]!
  $where: VehicleOrderWhereInput!
) {
  vehicleOrders(orderBy: $orderBy, where: $where) {
    id
    price
    dealer {
      vehicleVariant {
        vehicle {
          name
        }
        name
      }
      vehicleColor {
        name
        code
        images {
          id
          image {
            id
            url
          }
        }
      }
      dealer {
        id
      }
      id
      prices {
        amount
        createdAt
        id
        category {
          name
          id
        }
      }
    }
    status
    order {
      user {
        id
        email
        name
        phoneNumber
        addresses {
          id
          phoneNumber
          pinCode
          state
          town
          address
          district
          name
        }
      }
      id
      createdAt
    }
    createdAt
  }
}

query VehicleOrdersCount($where: VehicleOrderWhereInput!) {
  vehicleOrdersCount(where: $where)
}

query TestDriveOrders(
  $where: TestDriveOrderWhereInput!
  $orderBy: [TestDriveOrderOrderByInput!]!
) {
  testDriveOrders(where: $where, orderBy: $orderBy) {
    id
    price
    dealer {
      vehicleVariant {
        vehicle {
          name
        }
        name
      }
      vehicleColor {
        name
        code
        images {
          id
          image {
            id
            url
          }
        }
      }
      dealer {
        id
      }
      id
      price
    }
    status
    order {
      user {
        id
        email
        name
        phoneNumber
        addresses {
          id
          phoneNumber
          pinCode
          state
          town
          address
          district
          name
        }
      }
      id
      createdAt
    }
    createdAt
  }
}

query TestDriveOrdersCount($where: TestDriveOrderWhereInput!) {
  testDriveOrdersCount(where: $where)
}

mutation UpdateProductOrder(
  $where: ProductOrderWhereUniqueInput!,
  $data: ProductOrderUpdateInput!) {
  updateProductOrder(where: $where, data: $data) {
    id
  }
}

mutation UpdateVehicleOrder(
  $where: VehicleOrderWhereUniqueInput!
  $data: VehicleOrderUpdateInput!
) {
  updateVehicleOrder(where: $where, data: $data) {
    id
  }
}

mutation UpdateTestDriveOrder($where: TestDriveOrderWhereUniqueInput!, $data: TestDriveOrderUpdateInput!) {
  updateTestDriveOrder(where: $where, data: $data) {
    id
  }
}

mutation CreateOrderRejectionByDealer(
  $data: OrderRejectionByDealerCreateInput!
) {
  createOrderRejectionByDealer(data: $data) {
    id
  }
}
