query ProductDealerStockRequests {
  productDealerStockRequests {
    id
    accepted
    type
    totalPrice
    stock
    modifiedAt
    productVariant {
      name
      id
      gallery {
        id
        file
      }
    }
  }
}

query VehicleDealerStockRequests($where: VehicleDealerStockRequestWhereInput!, $orderBy: [VehicleDealerStockRequestOrderByInput!]!, $take: Int, $skip: Int!) {

  vehicleDealerStockRequests(where: $where, orderBy: $orderBy, take: $take, skip: $skip) {
    id
    accepted
    type
    totalPrice
    stock
    vehicleColor {
      id
      name
      gallery {
        id
        file
      }
    }
    vehicleVariant {
      id
      name
    }
  }
}

query Query($where: VehicleDealerStockRequestWhereInput!) {
  vehicleDealerStockRequestsCount(where: $where)
}