query Vehicles {
  vehicles {
    variants {
      price
      name
      vehicle {
        name
        brand {
          name
          id
        }
        type {
          name
          description
          id
        }
        id
      }
      colors {
        id
        name
        code
        images {
          image {
            url
          }
        }
      }
      id
    }
  }
}

mutation CreateVehicleDealerStockRequest($data: VehicleDealerStockRequestCreateInput!) {
  createVehicleDealerStockRequest(data: $data) {
    type
    stock
    dealer_prices
  }
}

mutation CreateVehicleTestDriveDealerStockRequest($data: TestDriveDealerStockRequestCreateInput!) {
  createTestDriveDealerStockRequest(data: $data) {
    available
    price
  }
}