query ProductVariants(
  $skip: Int!
  $take: Int
  $where: ProductVariantWhereInput!
  $location: [Float!]
  $orderBy: [ProductVariantOrderByInput!]!
) {
  productVariants(skip: $skip, take: $take, where: $where, orderBy: $orderBy) {
    id
    name
    availableProductDealer(location: $location)
    prices {
      amount
      category {
        name
        description
      }
    }
    specifications {
      id
      isKeyFeature
      name
      specification {
        image {
          url
        }
        id
        name
        description
        unit
      }
      type
      intValue
      stringValue
      category {
        id
        name
        description
      }
    }
    totalPrice
    images {
      image {
        url
        width
        id
      }
    }
    gallery {
      file
      type
      index
    }
    product {
      brand {
        id
        name
        logo {
          id
          extension
          url
        }
      }
      name
      description
      longDescription
      id
      type {
        id
        name
        description
      }
      specifications {
        id
        isKeyFeature
        name
        specification {
          image {
            url
          }
          id
          name
          description
          unit
        }
        type
        intValue
        stringValue
        category {
          id
          name
          description
        }
      }
    }
    tags {
      id
      title
      description
    }
    images {
      id
      name
      image {
        url
      }
    }
  }
}

query ProductVariantsCount($where: ProductVariantWhereInput!) {
  productVariantsCount(where: $where)
}

query ProductVariant(
  $where: ProductVariantWhereUniqueInput!
  $location: [Float!]
) {
  productVariant(where: $where) {
    id
    name
    availableProductDealer(location: $location)
    prices {
      amount
      category {
        name
        description
      }
    }
    specifications {
      id
      isKeyFeature
      name
      specification {
        image {
          url
        }
        id
        name
        description
        unit
      }
      type
      intValue
      stringValue
      category {
        id
        name
        description
      }
    }
    totalPrice
          images {
        image {
          url
          width
          id
        }
      }
    gallery {
      file
      type
      index
    }
    product {
      brand {
        id
        name
        logo {
          id
          extension
          url
        }
      }
      name
      description
      longDescription
      id
      type {
        id
        name
        description
      }
      specifications {
        id
        isKeyFeature
        name
        specification {
          image {
            url
          }
          id
          name
          description
          unit
        }
        type
        intValue
        stringValue
        category {
          id
          name
          description
        }
      }
    }
    tags {
      id
      title
      description
    }
    images {
      id
      name
      image {
        url
      }
    }
  }
}

query ProductTypes {
  productTypes {
    id
    name
  }
}

query VehicleVariants(
  $where: VehicleVariantWhereInput!
  $orderBy: [VehicleVariantOrderByInput!]!
  $skip: Int!
  $take: Int
) {
  vehicleVariantsCount(where: $where)
  vehicleVariants(where: $where, orderBy: $orderBy, skip: $skip, take: $take) {
    prices {
      amount
      category {
        name
        description
      }
    }
    colors {
      id
      code
      images {
        name
        image {
          url
          width
          id
        }
      }
      name
    }
    name
    default
    id
    totalPrice
    vehicle {
      brand {
        id
        name
      }
      name
      id
      type {
        name
      }
    }
  }
}

query VehicleVariantsCount($where: VehicleVariantWhereInput!) {
  vehicleVariantsCount(where: $where)
}

mutation CreateVehicleDealerStockRequest(
  $data: VehicleDealerStockRequestCreateInput!
) {
  createVehicleDealerStockRequest(data: $data) {
    type
    stock
    totalPrice
  }
}

query VehicleDealersCount($where: VehicleDealerWhereInput!) {
  vehicleDealersCount(where: $where)
}

query VehicleDealers($where: VehicleDealerWhereInput!, $take: Int, $skip: Int!) {
  vehicleDealersCount(where: $where)
  vehicleDealers(where: $where, take: $take, skip: $skip) {
    vehicleColor {
      id
      name
      code
      images {
        id
        image {
          url
        }
      }
    }
    vehicleVariant {
      id
      name
      modifiedAt
      vehicle {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }

    id
    stock
    prices {
      id
      amount
      category {
        id
        name
      }
    }
    totalPrice
    guarantees {
      name
      id
      description
    }
  }
}

mutation CreateVehicleDealer($data: VehicleDealerCreateInput!) {
  createVehicleDealer(data: $data) {
    id
  }
}

query PriceCategories {
  priceCategories {
    id
    name
    description
    createdAt
    modifiedAt
  }
}

mutation UpdateVehicleDealer(
  $where: VehicleDealerWhereUniqueInput!
  $data: VehicleDealerUpdateInput!
) {
  updateVehicleDealer(where: $where, data: $data) {
    vehicleColor {
      id
      name
      code
      images {
        id
        image {
          url
        }
      }
    }
    vehicleVariant {
      id
      name
      modifiedAt
      vehicle {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }
    id
    stock
    prices {
      id
      amount
      category {
        id
        name
      }
    }
    totalPrice
    guarantees {
      name
      id
      description
    }
  }
}

mutation UpdatePrices($data: [PriceUpdateArgs!]!) {
  updatePrices(data: $data) {
    id
  }
}

query TestDriveDealers(
  $where: TestDriveDealerWhereInput!
  $take: Int
  $skip: Int!
) {
  testDriveDealers(where: $where, take: $take, skip: $skip) {
    vehicleColor {
      id
      name
      code
      images {
        id
        image {
          url
        }
      }
    }
    vehicleVariant {
      id
      name
      modifiedAt
      vehicle {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }
    price
    id
  }
  testDriveDealersCount(where: $where)
}

mutation UpdateTestDriveDealer(
  $where: TestDriveDealerWhereUniqueInput!
  $data: TestDriveDealerUpdateInput!
) {
  updateTestDriveDealer(where: $where, data: $data) {
    vehicleColor {
      id
      name
      code
      images {
        id
        image {
          url
        }
      }
    }
    vehicleVariant {
      id
      name
      modifiedAt
      vehicle {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }
    price
    id
  }
}

mutation CreateTestDriveDealer($data: TestDriveDealerCreateInput!) {
  createTestDriveDealer(data: $data) {
    id
  }
}

query ProductDealers($where: ProductDealerWhereInput!, $take: Int, $skip: Int!) {
  productDealersCount(where: $where)
  productDealers(where: $where, take: $take, skip: $skip) {
    productVariant {
      id
      name
      modifiedAt
      images {
        id
        image {
          url
        }
      }
      product {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }
    id
    stock
    prices {
      id
      amount
      category {
        id
        name
      }
    }
    totalPrice
    guarantees {
      name
      id
      description
    }
  }
}

mutation CreateProductDealer($data: ProductDealerCreateInput!) {
  createProductDealer(data: $data) {
    id
  }
}

mutation UpdateProductDealer(
  $where: ProductDealerWhereUniqueInput!
  $data: ProductDealerUpdateInput!
) {
  updateProductDealer(where: $where, data: $data) {
    productVariant {
      product {
        brand {
          id
          name
        }
        id
        name
        description
      }
      modifiedAt
      id
      name
    }
    id
    stock
    totalPrice
    prices {
      amount
      id
      category {
        id
        name
      }
    }
    guarantees {
      id
      description
      name
    }
  }
}

mutation CreateProductDealerStockRequest(
  $data: ProductDealerStockRequestCreateInput!
) {
  createProductDealerStockRequest(data: $data) {
    type
    stock
    totalPrice
  }
}

query VehicleFilterData {
  vehicleTypes {
    id
    name
    description
  }
  brands {
    id
    name
    type
  }
}

query ProductFilterData {
  productTypes {
    id
    name
    description
  }
  brands {
    id
    name
    type
  }
}