query Vehicles {
  vehicles {
    variants {
      price
      name
      vehicle {
        name
        brand {
          name
          id
        }
        type {
          name
          description
          id
        }
        id
      }
      colors {
        id
        name
        code
        images {
          image {
            url
          }
        }
      }
      id
    }
  }
}

mutation CreateVehicleDealerStockRequest(
  $data: VehicleDealerStockRequestCreateInput!
) {
  createVehicleDealerStockRequest(data: $data) {
    type
    stock
    totalPrice
  }
}

query VehicleDealers($where: VehicleDealerWhereInput!) {
  vehicleDealers(where: $where) {
    vehicleColor {
      id
      name
      code
      images {
        id
        image {
          url
        }
      }
    }
    vehicleVariant {
      id
      name
      modifiedAt
      price
      vehicle {
        brand {
          id
          name
        }
        name
        id
        description
      }
    }

    id
    stock
    prices {
      id
      amount
      category {
        id
        name
      }
    }
    totalPrice
  }
}
